name: 'Cypress fixtures'
on: pull_request # For testing purposes
# Every Monday at 1PM UTC (9AM EST)
# on:
#   schedule:
#     - cron: 0 13 * * 1

jobs:
  update_fixtures:
    runs-on: ubuntu-latest
    name: Create PR with cypress fixtures
    steps:
      - name: Checkout local repo
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Get date
        run: echo "CURRENT_DATE=$(date +'%d-%m-%Y')" >> $GITHUB_ENV

      - name: Set branch name
        run: echo "CYPRESS_FIXTURES_BRANCH=feature/e2e-$CURRENT_DATE" >> $GITHUB_ENV

      - name: Create new branch
        run: |
          echo "Creating $CYPRESS_FIXTURES_BRANCH"
          git checkout -b $CYPRESS_FIXTURES_BRANCH
          git config --global user.email "cypress-fixtures-spy@bloomandwild.com"
          git config --global user.name "Cypress Fixtures Spy"
          git push -u origin $CYPRESS_FIXTURES_BRANCH

      - name: Run record
        # TODO
        run: |
          touch hello-world.txt
          echo hello world! >> hello-world.txt
          git add .
          git commit -m  "Fixtures pulled at `CURRENT_DATE`"
          git push origin $CYPRESS_FIXTURES_BRANCH

      - name: Create PR
        env:
          TRANSLATION_BRANCH_NAME: $CYPRESS_FIXTURES_BRANCH
          BASE_BRANCH_NAME: 'dev'
        uses: peter-evans/create-pull-request@v4
        with:
          title: '[E2E] Cypress fixtures pulled $CURRENT_DATE'
          branch: $CYPRESS_FIXTURES_BRANCH
          base: 'dev'
          delete-branch: true
