name: 'Sync cypress fixtures'
on: pull_request # For testing purposes
# Every Monday at 1PM UTC (9AM EST)
# on:
#   schedule:
#     - cron: 0 13 * * 1

jobs:
  update_fixtures:
    runs-on: [self-hosted, linux, x64, bwmedium]
    name: Create PR with cypress fixtures
    steps:
      - name: Checkout local repo
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Get date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Set branch name
        run: echo "CYPRESS_FIXTURES_BRANCH=eature/e2e-{{$CURRENT_DATE}}" >> $GITHUB_ENV

      - name: Create new branch
        run: |
          "echo "Creating $CYPRESS_FIXTURES_BRANCH"
          git checkout b $CYPRESS_FIXTURES_BRANCH
          git config --global user.email "cypress-fixtures-spy@bloomandwild.com"
          git config --global user.name "Cypress Fixtures Spy"
          git push -u origin $CYPRESS_FIXTURES_BRANCH
